### ISSUE TITLE
Build out the UX for managing submissions

### ISSUE THREAD

**Issue by jnywong** [2i2c-org/unnamed-thingity-thing#101]
### Context

From the [Slack channel](https://2i2c.slack.com/archives/C06RX73KF2R/p1728329340238629?thread_ts=1728039095.480429&cid=C06RX73KF2R), there is feedback on the submission process that needs to be improved.

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/103
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/104
- [x] Redirect to 'My Submissions' page once a submission is uploaded
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/121
```

### Submission text

[^1]: Upload your submission:
Select a zip file, containing the zarr dataset(s) to be evaluated, and upload it. For more detailed instructions check out readthedocs {link}.

Submission requirements:
1. The submission should be a single zip file containing a single Zarr-2 file with the following structure:
   - submission.zarr
     - /<test_volume_name>
        - /<label_name>
2. The names of the test volumes and labels should match the names of the test volumes and labels in the test data.
3. Each label volume should be either A) a 3D binary volume with the same shape and scale as the corresponding test volume, or B) instance IDs per object.
4. The scale for all volumes is 8x8x8 nm/voxel, except as otherwise specified.

**Comment by jnywong** [comment]
Closing this out since only #121 remains.
