### ISSUE TITLE
[EPIC] Make a deployment for use with the OpenOrganelle Challenge

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/unnamed-thingity-thing#17]
The goal is to design and make a deployment for the openorganelle challenge. It should support the following:

1. Continuous Deployment so deployments can happen by merging a PR
2. Separation between the deployment and the open source project, so we don't end up accidentally hardcoding things about the challenge into the open source project
3. Supports at least two installations - staging and prod.

I'll work with @GeorgianaElena in making this happen. In particular, I think this is a great way for her to take fuller ownership of the process! 

```[tasklist]
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/18
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/19
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/20
- [ ] https://github.com/2i2c-org/segmentation-challenge-deploy/issues/2
- [ ] https://github.com/2i2c-org/segmentation-challenge-deploy/issues/3
- [ ] https://github.com/2i2c-org/segmentation-challenge-deploy/issues/7
```

## Definition of done

- [x] Cloud provider to use for this deployment is chosen
- [x] Kubernetes cluster created with a chosen method for this deployment
- [x] A way to make deployments with different settings for different deployments via GitHub actions is set up.

## Timeline

We should aim to keep the complexity of this in such a way that it can be implemented within one full sprint, cutting scope intentionally as needed.

## Next steps

- [x] Yuvi and @GeorgianaElena meet to have @GeorgianaElena make choices on how this would be done
- [x] Georgiana splits this out into tasks with just enough detail so others can monitor progress by looking at them without having to intentionally ask her. 
- [x] Yuvi unblocks Georgiana with clarification and prioritization questions as quickly as possible
- [x] We check in to see where we are at the end of this sprint
