### ISSUE TITLE
[EPIC] Setup helm chart for this project

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/unnamed-thingity-thing#9]
There are a couple of ways we can deploy this. But let's stick to keeping things familiar across 2i2c infrastructure, and use kubernetes. 

## Alternatives considered

- `systemd` units + `venv`. We'll have to build a deployment mechanism ourselves, and a way to bundle virtual envs appropriately. Don't want to do that
- Plain docker, no kubernetes. We do not have to bundle virtualenvs, but still need to setup a deployment mechanism ourselves. Simpler, but does not lean into the strengths of the 2i2c team.

This EPIC tracks setting up infrastructure for handling this deployment. It doesn't actually track doing the deployment itself.

```[tasklist]
### Tasks
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/10
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/11
- [ ] https://github.com/2i2c-org/unnamed-thingity-thing/issues/12
```
